### ISSUE TITLE
MG's Beat Blades Haruka does not even start on android xsystem4

### ISSUE THREAD

**Issue by KaroNiko** [kichikuou/xsystem4-android#5]
Whatever option you select on the start screen gives the error shown in the photo.
According to the compatibility chart, the original Japanese version of this game should work.
Thank you for your attention and dedication to the project.

![1710939408975](https://github.com/kichikuou/xsystem4-android/assets/163753361/e87fc5be-e1af-40bf-8a35-dd194935f348)

Edit: For the sake of truth, all my posts go back several weeks, but they remained invisible because my profile was flagged for some reason; fortunately, everything is okay now.

**Comment by kichikuou** [comment]
`SACTDX.Sound_GetGroupNum` is not used in the Japanese version, so the problem seems to be specific to the MG version. Unfortunately I do not have the MG version.

You might want to file an issue on the [xsystem4](https://github.com/nunuhara/xsystem4/issues) project since this is not an Android-specific issue.

(In fact, Haruka is Unknown in the [compatibility table](https://github.com/nunuhara/xsystem4/blob/master/game_compatibility.md).)

**Comment by KaroNiko** [comment]
Hey @kichikuou, sorry to bother you here but I didn't know how to PM you. Are you by any chance in contact with nunuhara? Did he ever talk to you about possible support for the english version by MG of Beat Blades Haruka? He never commented on my thread about this topic and I'm afraid he'll get annoyed if I name him directly and ask him questions. I know it's not your responsibility, but if you can tell me something about this I would be very grateful. Thank you, chief.

**Comment by kichikuou** [comment]
You can download an Android build with the fix [here](https://github.com/kichikuou/xsystem4-android/actions/runs/10245762547).

@nunuhara [noted](https://github.com/nunuhara/xsystem4/issues/154#issuecomment-2268196675) about movie glitches, but probably in Android moves will simply fail to play because it is not built with VC-1 codec support.
